# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: real_world
    ports:
      - 5433:5432
    volumes:
      - ./backups:/home/backups

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

